import glob, os, gc, warnings, random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings('ignore')
random.seed(42)
np.random.seed(42)

CSV_FOLDER = './MachineLearningCVE'
LABEL_COL = 'Label'
RANDOM_STATE = 42
TEST_SIZE = 0.30
SYNTHETIC_PER_CLASS = 3

csv_files = sorted(glob.glob(os.path.join(CSV_FOLDER, '*.csv')))
dfs = []
for f in csv_files:
    for chunk in pd.read_csv(f, chunksize=50000, low_memory=False, encoding='latin-1'):
        dfs.append(chunk)
    gc.collect()

df = pd.concat(dfs, ignore_index=True)
print(f"Loaded: {len(df)} rows")

df.columns = df.columns.str.strip()
drop_cols = [c for c in ['Flow ID','Source IP','Destination IP','Timestamp',
                          'Src IP','Dst IP','src_ip','dst_ip'] if c in df.columns]
if drop_cols:
    df.drop(columns=drop_cols, inplace=True)
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(axis=1, thresh=int(len(df) * 0.5), inplace=True)
df.dropna(axis=0, inplace=True)
df.drop_duplicates(inplace=True)

le = LabelEncoder()
df['label_enc'] = le.fit_transform(df[LABEL_COL].astype(str))
class_names = le.classes_
n_classes = len(class_names)

X = df.drop(columns=[LABEL_COL, 'label_enc']).select_dtypes(include=[np.number])
y = df['label_enc']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

feature_cols = X.columns.tolist()

lines = []
for cls_idx in range(n_classes):
    cls_name = class_names[cls_idx]
    mask = (y_test == cls_idx)
    indices = np.where(mask)[0]
    if len(indices) < 2:
        print(f"{cls_name}: only {len(indices)} samples, using training set too")
        mask_train = (y_train == cls_idx)
        indices_train = np.where(mask_train)[0]
        all_idx = list(indices) + list(indices_train)
        if len(all_idx) < 2:
            print(f"  SKIP - not enough samples")
            continue
        indices = np.array(all_idx)
        X_use = pd.concat([X_test, X_train])
    else:
        X_use = X_test

    n_synth = min(SYNTHETIC_PER_CLASS, len(indices) * (len(indices) - 1) // 2)
    print(f"{cls_name:35s}: {len(indices)} real samples, generating {n_synth} synthetic")

    generated = 0
    attempts = 0
    while generated < n_synth and attempts < 100:
        attempts += 1
        i, j = np.random.choice(len(indices), size=2, replace=False)
        row_a = X_use.iloc[indices[i]].values.astype(float)
        row_b = X_use.iloc[indices[j]].values.astype(float)
        alpha = 0.3 + np.random.random() * 0.4
        synthetic = alpha * row_a + (1 - alpha) * row_b
        vals = ",".join(f"{v:.6f}" for v in synthetic)
        lines.append(f"{cls_name}|{vals}")
        generated += 1

print(f"\nTotal synthetic vectors: {len(lines)}")

with open("smote_test_vectors.txt", "w") as f:
    f.write("# SMOTE-synthetic CICIDS 2017 test vectors\n")
    f.write("# Generated by interpolating between real test-set samples (alpha in [0.3, 0.7])\n")
    f.write("# Each line: LABEL|78 comma-separated values (raw, unscaled)\n")
    f.write(f"# Features ({len(feature_cols)}): {', '.join(feature_cols[:8])}...\n")
    f.write("# ========================================================\n")
    for line in lines:
        f.write(line + "\n")

print("Saved to smote_test_vectors.txt")
